#!/bin/bash

source $HOME/.syncrc

#premet d'utiliser rm sans les confirmations
RM=/bin/rm

#trace pour indiquer que le programme s'est executé
echo "bonjour"
#Touch pour modifier la date de dernière utilisation de bonjour parce que l'éxecution ne 
#la modifie pas et que l'on en a besoin pour bonsoir.
touch ${bonjour}

#suppression des fichiers supprimés ou déplacés par les commandes mouve ou remouve
remouve=
cd ${location}
cat bonjour.mv bonjour.rm | xargs "$RM" -rf


#extraction de l'archive archive.tar dans $HOME
#l'argument P permet de manipuler des chemins absolus pour écrire les fichiers directement aux bons endroits
tar -xPf "${locate_archive}"
