#! /bin/bash
### Informations: "man mouve" ###

#CONFIGURATION DES OPTIONS DE MV:
##Fichier config: ~/.syncrc
###Par défault on appelle la variable: 'Info_and_safe_mv=mv -i'
. $HOME/.syncrc

#CONDITIONS ET GESTIONS D'ERREUR
## Test de présence du fichier de configuration
if [ ! -f "$HOME/.syncrc" ]; then
echo Fichier de configuration introuvable
man mouve
exit 1
fi

##Test d'absence d'argument:
if [ "$#" -eq 0 ]; then 
 echo Erreur: Il manque des arguments à la fonction mouve
 mouve -h #renvoie l'aide
 exit 0
fi 

##Test de présence de l'option -h en argument:
if [ "$1" == "--help" ]  || [ "$1" == "-h" ] ; then 
  echo "Usage: $(basename "$0") [-h][--help] [Source] [Destination]"
  echo "Informations: « man mouve »"
  exit 0
fi

# ASSIGNATION A DES VARIABLES:
##Le but ici est d'alléger le main et de récuperer le
##chemin de fichier avant modification:

dir=$(pwd)/   

##Parametres>=2 et actualisation de atime du fichier déplacé
  while [ "$#" -gt 1 ]
    do
      mv "${option_mv}" "$1" "${@: -1}" || exit 1
      echo "$dir$1" >> ~/bonjour.mv
      touch "$2" #astuce pour actualiser les dates de modification du fichier
      shift
    done
