#! /bin/bash
###Informations: "man remouve"###

#CONFIGURATION DES OPTIONS DE MV:
##Fichier config: ~/.syncrc
###Par défault on appelle la variable: 'Force_rm=rm -rf'
. ~/.syncrc

#CONDITIONS ET GESTION D'ERREURS:
##Test d'absence d'argument:
if [ "$#" -eq 0 ] ; then 
 echo "Erreur: Agruments manquants"
 remouve -h #renvoie l'aide
 exit 0
fi 

##Test de présence de l'option -h en argument
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then 
  echo "Usage: `basename $0` [-h][--help] [Fichier à supprimer]"
  echo "Informations: « man remouve »"
  exit 0
fi

# ASSIGNATION A DES VARIABLES:
##Le but ici est de récuperer le chemin d'accés
##du dossier d'où on à supprimé le fichier
dir=$(pwd)/

#MAIN
##Suppresion et sauvegarde du chemin d'accès du fichier supprimé: 
if [ ! -e "$dir$1" ] #si le fichier n'existe pas
then
echo "Erreur: Le fichier $dir$1 n'existe pas."
else #si le fichier existe
while [ "$#" -gt 0 ] #parametres>=1
do
  rm ${Force_rm} $1
  echo "$dir$1" >> ~/bonjour.rm
  shift
done
fi
